/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.phieumuon;

import QLTVController.PhieuMuonController;
import Util.CustomTablePhieuMuon;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author WIN1064
 */
public class QuanLyPhieuMuon extends javax.swing.JPanel {

    PhieuMuonController pmc = new PhieuMuonController();
    int selectedRow = -1;
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    String keywords = "";
    String tongPhieu, tienGiu;
    public static QuanLyPhieuMuon qlpm;

    /**
     * Creates new form QuanLyPhieuMuon
     */
    public QuanLyPhieuMuon() {
        initComponents();
        LuuDuLieu.dsPMCT = pmc.getPMCT();
        qlpm = this;
        loadTable();
        jDateChooserTu.setDateFormatString("dd-MM-yyyy");
        jDateChooserDen.setDateFormatString("dd-MM-yyyy");
        jTableMuonSach.getTableHeader().setDefaultRenderer(new StyleHeaderTable());
        CustomTablePhieuMuon ct = new CustomTablePhieuMuon();
        jTableMuonSach.getColumnModel().getColumn(2).setPreferredWidth(200);
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableMuonSach.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTableMuonSach.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void loadTable() {
        jTableMuonSach.setModel(new CustomTablePhieuMuon());
        CustomTablePhieuMuon ct = new CustomTablePhieuMuon();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        jTableMuonSach.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableMuonSach.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        jTableMuonSach.getColumnModel().getColumn(2).setPreferredWidth(200);
        thongKe();
    }

    public void thongKe() {
        tongPhieu = Integer.toString(LuuDuLieu.dsPMCT.size());
        jLabelTongPhieu.setText("Tổng số phiếu : " + tongPhieu);
        tienGiu = Integer.toString((int) LuuDuLieu.dsPMCT.stream().mapToInt(s -> s.getTienCoc()).sum());
        jLabelTienGiu.setText("Tiền đang giữ :" + tienGiu);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooserTu = new com.toedter.calendar.JDateChooser();
        jDateChooserDen = new com.toedter.calendar.JDateChooser();
        jButtonTaiLai = new javax.swing.JButton();
        jButtonLoc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonXacNhan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMuonSach = new javax.swing.JTable();
        jButtonTimKiem = new javax.swing.JButton();
        jTextKeyWord = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelTienGiu = new javax.swing.JLabel();
        jLabelTongPhieu = new javax.swing.JLabel();

        jButtonTaiLai.setBackground(new java.awt.Color(0, 204, 204));
        jButtonTaiLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset-20.png"))); // NOI18N
        jButtonTaiLai.setText("Tải lại bảng");
        jButtonTaiLai.setBorder(null);
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });

        jButtonLoc.setBackground(new java.awt.Color(0, 204, 204));
        jButtonLoc.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter-20.png"))); // NOI18N
        jButtonLoc.setText("Lọc");
        jButtonLoc.setBorder(null);
        jButtonLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocActionPerformed(evt);
            }
        });

        jLabel2.setText("Đến ngày");

        jLabel1.setText("Từ ngày");

        jButtonXacNhan.setBackground(new java.awt.Color(0, 204, 204));
        jButtonXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return-user-book.png"))); // NOI18N
        jButtonXacNhan.setText("Xác nhận đã trả sách");
        jButtonXacNhan.setBorder(null);
        jButtonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhanActionPerformed(evt);
            }
        });

        jTableMuonSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMuonSach.setFocusable(false);
        jTableMuonSach.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableMuonSach.setRowHeight(25);
        jTableMuonSach.setSelectionBackground(new java.awt.Color(255, 0, 102));
        jTableMuonSach.setShowVerticalLines(false);
        jTableMuonSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMuonSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMuonSach);

        jButtonTimKiem.setBackground(new java.awt.Color(0, 204, 204));
        jButtonTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.setBorder(null);
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Thống kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabelTienGiu.setText("Tiền đang giữ :");

        jLabelTongPhieu.setText("Tống số phiếu :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTongPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTienGiu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTongPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTienGiu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserTu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jDateChooserDen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(331, 331, 331)
                        .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateChooserTu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserDen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMuonSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMuonSachMouseClicked
        selectedRow = jTableMuonSach.getSelectedRow();
        LuuDuLieu.currentPhieuMuonChiTiet = LuuDuLieu.dsPMCT.get(selectedRow);
    }//GEN-LAST:event_jTableMuonSachMouseClicked

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Chọn phiếu muốn xác nhận");
        } else {
            int op = JOptionPane.showConfirmDialog(null,
                    "Bạn xác nhận phiếu có mã " + LuuDuLieu.currentPhieuMuonChiTiet.getMaPhieu() + " đã trả sách !", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                if (pmc.updateDaTra(LuuDuLieu.currentPhieuMuonChiTiet.getMaPhieu()) == 1) {
                    LuuDuLieu.dsPMCT = pmc.getPMCT();
                    loadTable();
                    LuuDuLieu.dsPTCT = pmc.getPMCTDaTra();
                    QuanLyPhieuTra.qlpt.loadTable();
                    selectedRow = -1;
                }

            }
        }
    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        keywords = jTextKeyWord.getText() + "";
        if (jDateChooserTu.getDate() != null && jDateChooserDen.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tuNgay = sdf.format(jDateChooserTu.getDate());
            String denNgay = sdf.format(jDateChooserDen.getDate());
            if (keywords.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vòng lòng nhập từ khóa");
            }
            else
            LuuDuLieu.dsPMCT = pmc.locPhieu(tuNgay, denNgay, keywords);
        } else {
            if (keywords.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Vòng lòng nhập từ khóa");
            } else {
                LuuDuLieu.dsPMCT = pmc.locPhieu(null, null, keywords);
            }
        }
        loadTable();
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocActionPerformed
        if (jDateChooserDen.getDate() == null || jDateChooserTu.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Bạn phải chọn ngày để lọc");
        } else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tuNgay = sdf.format(jDateChooserTu.getDate());
            String denNgay = sdf.format(jDateChooserDen.getDate());
            LuuDuLieu.dsPMCT = pmc.locPhieu(tuNgay, denNgay, keywords);
            loadTable();
        }
    }//GEN-LAST:event_jButtonLocActionPerformed

    private void jButtonTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaiLaiActionPerformed
        LuuDuLieu.dsPMCT = pmc.getPMCT();
        loadTable();
        jDateChooserDen.setDate(null);
        jDateChooserTu.setDate(null);
        jTextKeyWord.setText("");
        keywords = "";
        selectedRow = -1;
    }//GEN-LAST:event_jButtonTaiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoc;
    private javax.swing.JButton jButtonTaiLai;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JButton jButtonXacNhan;
    private com.toedter.calendar.JDateChooser jDateChooserDen;
    private com.toedter.calendar.JDateChooser jDateChooserTu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTienGiu;
    private javax.swing.JLabel jLabelTongPhieu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMuonSach;
    private javax.swing.JTextField jTextKeyWord;
    // End of variables declaration//GEN-END:variables
}
