/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinhvien;

import QLTVController.SinhVienController;
import QLTVModel.SinhVienClass;
import Util.CustomTableSinhVien;
import Util.LuuDuLieu;
import Util.StyleHeaderTable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author WIN1064
 */
public class QuanLySinhVien extends javax.swing.JPanel {

    int selectedRow = -1;
    SinhVienController svc = new SinhVienController();
    ArrayList<String> dsNganh = new ArrayList<String>();
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    public static QuanLySinhVien qlsinhvien;
    String tongSV;

    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() {
        initComponents();
        qlsinhvien = this;
        ButtonGroup btn = new ButtonGroup();
        btn.add(jRdoNu);
        btn.add(jRdoNam);
        ButtonGroup btn2 = new ButtonGroup();
        btn2.add(jRdoKichHoat);
        btn2.add(jRdoTat);
        jRdoKichHoat.setSelected(true);
        jRdoNam.setSelected(true);
        LuuDuLieu.dsSV = svc.getSV();
        String nganh1 = "Công nghệ thông tin";
        String nganh2 = "Kinh tế";
        String nganh3 = "Điện tử";
        String nganh4 = "Du lịch";
        dsNganh.add(nganh1);
        dsNganh.add(nganh2);
        dsNganh.add(nganh3);
        dsNganh.add(nganh4);
        jDateNS.setDateFormatString("dd/MM/yyyy");
        jComboBoxNganh.setModel(
                new DefaultComboBoxModel(dsNganh.toArray()));
        jTableSinhVien.getTableHeader().setDefaultRenderer(new StyleHeaderTable());
        jTableSinhVien.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        renderer.setHorizontalAlignment(JLabel.CENTER);
        CustomTableSinhVien ct = new CustomTableSinhVien();
        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableSinhVien.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        loadTable();
    }

    public void loadTable() {
        jTableSinhVien.setModel(new CustomTableSinhVien());
        CustomTableSinhVien ct = new CustomTableSinhVien();
        jTableSinhVien.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        for (int i = 0; i < ct.getColumnCount(); i++) {
            jTableSinhVien.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        thongKe();
    }

    public void xoaTrang() {
        jTextMaSV.setText("");
        jTextTenSV.setText("");
        jComboBoxNganh.setSelectedIndex(0);
        jDateNS.setDate(null);
        jRdoNam.setSelected(true);
        jTextSDT.setText("");
        jTextEmail.setText("");
    }

    public void thongKe() {
        tongSV = Integer.toString(LuuDuLieu.dsSV.size());
        jLabelTongSV.setText("Tổng số sinh viên : " + tongSV);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSinhVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonXoa = new javax.swing.JButton();
        jButtonThemSach = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jTextKeyWords = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextTenSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextMaSV = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jDateNS = new com.toedter.calendar.JDateChooser();
        jRdoNam = new javax.swing.JRadioButton();
        jRdoNu = new javax.swing.JRadioButton();
        jComboBoxNganh = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jRdoKichHoat = new javax.swing.JRadioButton();
        jRdoTat = new javax.swing.JRadioButton();
        jButtonTaiLai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelTongSV = new javax.swing.JLabel();

        jTableSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jTableSinhVien.setFocusable(false);
        jTableSinhVien.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableSinhVien.setRowHeight(25);
        jTableSinhVien.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTableSinhVien.setShowVerticalLines(false);
        jTableSinhVien.getTableHeader().setReorderingAllowed(false);
        jTableSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSinhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSinhVien);

        jButtonXoa.setBackground(new java.awt.Color(0, 204, 204));
        jButtonXoa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-student-20.png"))); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.setBorder(null);
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });

        jButtonThemSach.setBackground(new java.awt.Color(0, 204, 204));
        jButtonThemSach.setForeground(new java.awt.Color(255, 255, 255));
        jButtonThemSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jButtonThemSach.setText("Thêm sinh viên");
        jButtonThemSach.setBorder(null);
        jButtonThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemSachActionPerformed(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setIcon(new javax.swing.ImageIcon("E:\\JavaProject\\ThuVien\\img\\search.png")); // NOI18N
        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.setBorder(null);
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonSua.setBackground(new java.awt.Color(0, 204, 204));
        jButtonSua.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modify-student-20.png"))); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setBorder(null);
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Email");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên sinh viên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ngày sinh");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Số điện thoại");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Ngành học");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã sinh viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Giới tính");

        jTextMaSV.setEditable(false);

        jRdoNam.setText("Nam");

        jRdoNu.setText("Nữ");

        jComboBoxNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Trạng thái");

        jRdoKichHoat.setText("Kích hoạt");

        jRdoTat.setText("Tắt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jTextTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRdoNu)
                                .addComponent(jRdoTat))
                            .addComponent(jDateNS, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRdoNam)
                            .addComponent(jComboBoxNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jRdoKichHoat)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateNS, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRdoNam)
                    .addComponent(jRdoNu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRdoKichHoat)
                    .addComponent(jRdoTat))
                .addContainerGap())
        );

        jButtonTaiLai.setBackground(new java.awt.Color(0, 204, 204));
        jButtonTaiLai.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset-20.png"))); // NOI18N
        jButtonTaiLai.setText("Tải lại");
        jButtonTaiLai.setBorder(null);
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Thống kê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabelTongSV.setText("Tổng số sinh viên :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTongSV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTongSV)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSinhVienMouseClicked
        try {
            selectedRow = jTableSinhVien.getSelectedRow();
            LuuDuLieu.currentSV = LuuDuLieu.dsSV.get(selectedRow);
            jTextMaSV.setText(LuuDuLieu.currentSV.getMaSV().trim() + "");
            jTextTenSV.setText(LuuDuLieu.currentSV.getTenSV().trim() + "");
            jComboBoxNganh.setSelectedItem(LuuDuLieu.currentSV.getNganhHoc());
            //            Date date = new SimpleDateFormat("dd-MM-yyyy").parse(s.getNgaySinh());
            //            Calendar cal = Calendar.getInstance();
            //            cal.setTime(date);
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(LuuDuLieu.currentSV.getNgaySinh());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            ((JTextField) jDateNS.getDateEditor().getUiComponent()).setText(sdf.format(date));
            if (LuuDuLieu.currentSV.getGioiTinh().trim().equalsIgnoreCase("Nam")) {
                jRdoNam.setSelected(true);
            } else {
                jRdoNu.setSelected(true);
            }
            if (LuuDuLieu.currentSV.getTrangThai() == 0) {
                jRdoKichHoat.setSelected(true);

            } else {
                jRdoTat.setSelected(true);
            }
            jTextSDT.setText(LuuDuLieu.currentSV.getSDT().trim() + "");
            jTextEmail.setText(LuuDuLieu.currentSV.getEmail().trim() + "");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jTableSinhVienMouseClicked

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
        selectedRow = jTableSinhVien.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Phải chọn dòng muốn xóa");
        } else {
            int op = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa sinh viên này?", "Xác nhận",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            if (op == 0) {
                SinhVienClass s = LuuDuLieu.dsSV.get(selectedRow);
                if (svc.kiemTraSinhVien_PhieuMua(s.getMaSV()) == 0 || svc.kiemTraSinhVien_PhieuMuon(s.getMaSV()) == 0) {
                    System.out.println("Okela");
                    JOptionPane.showMessageDialog(null, "Không thể xóa sinh viên do sinh viên đã có trong hệ thống phiếu");
                } else {
                    if (svc.xoaSV(s) == 1) {
                        xoaTrang();
                        selectedRow = -1;
                        LuuDuLieu.dsSV = svc.getSV();
                        loadTable();
                         JOptionPane.showMessageDialog(null, "Xóa thành công");
                    }

                }

            }
        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemSachActionPerformed

        ThemSinhVien ts = new ThemSinhVien();
        ts.setVisible(true);
    }//GEN-LAST:event_jButtonThemSachActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed

        LuuDuLieu.dsSV = svc.timKiem(jTextKeyWords.getText());
        loadTable();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        selectedRow = jTableSinhVien.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Phải chọn sinh viên cần sửa");

        } else {
            int op = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn sửa thông tin sinh viên này?", "Xác nhận",
                    JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                String gioiTinh = "";
                if (jRdoNam.isSelected()) {
                    gioiTinh = "Nam";
                } else {
                    gioiTinh = "Nữ";
                }
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(jDateNS.getDate());
                int tinhTrang = 0;
                if (jRdoKichHoat.isSelected()) {
                    tinhTrang = 0;
                } else {
                    tinhTrang = 1;
                }
                SinhVienClass s = new SinhVienClass();
                try {
                    s.setMaSV(jTextMaSV.getText());
                    s.setTenSV(jTextTenSV.getText());
                    s.setNganhHoc((String) jComboBoxNganh.getSelectedItem());
                    s.setNgaySinh(date);
                    s.setGioiTinh(gioiTinh);
                    s.setSDT(jTextSDT.getText());
                    s.setEmail(jTextEmail.getText());
                    s.setTrangThai(tinhTrang);

                    if (svc.suaSV(s) == 1) {
                        LuuDuLieu.dsSV = svc.getSV();
                        loadTable();
                        JOptionPane.showMessageDialog(null, "Sửa thành công");
                    }

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Sai thông tin :" + ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaiLaiActionPerformed
        LuuDuLieu.dsSV = svc.getSV();
        loadTable();
    }//GEN-LAST:event_jButtonTaiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonTaiLai;
    private javax.swing.JButton jButtonThemSach;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JComboBox<String> jComboBoxNganh;
    private com.toedter.calendar.JDateChooser jDateNS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTongSV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRdoKichHoat;
    private javax.swing.JRadioButton jRdoNam;
    private javax.swing.JRadioButton jRdoNu;
    private javax.swing.JRadioButton jRdoTat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSinhVien;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextKeyWords;
    private javax.swing.JTextField jTextMaSV;
    private javax.swing.JTextField jTextSDT;
    private javax.swing.JTextField jTextTenSV;
    // End of variables declaration//GEN-END:variables
}
